#!/bin/sh
#
# Copyright (c) 2016 Dmitry Dulepov <dmitry.dulepov@gmail.com>
# https://github.com/dmitryd/kali-yubikey
#
# /usr/share/initramfs-tools/hooks/yubikey

set -e

PREREQ=""
prereqs()
{
    echo "${PREREQ}"
}

case "${1}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/local/bin/ykchalresp /bin/ykchalresp
copy_exec /usr/local/bin/ykinfo /bin/ykinfo
copy_exec /usr/bin/uuidgen /bin/uuidgen
copy_exec /usr/bin/shred /bin/shred
copy_exec /usr/local/bin/gpgv1 /bin/gpgv1
#copy_exec /bin/busybox

